# Generated by Django 3.2.3 on 2021-06-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('address', models.CharField(max_length=300)),
                ('coordX', models.FloatField()),
                ('coordY', models.FloatField()),
                ('picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
